### PR TITLE
Riot.run raise exception after first call

### LINKED ISSUE #48: Make multiple calls to Riot.run throw
Since it's illegal to call Riot.run or Riot.start more than once, we should make it throw if it happens.

### Implementation Notes

One easy way to achieve this would be to have a global boolean ref that marks if the runtime has been started once, and we can check its false when we call Riot.run.

If its false, we flip it to true.

If it already is true, we can throw an exception.

### PR DESCRIPTION
**Pull request by julien-leclercq**
resolves #48

### CODE REVIEW

File: riot/riot.ml [hunk 1]
```diff
@@ -27,6 +33,7 @@ let run ?(rnd = Random.State.make_self_init ()) ?workers main =
   Scheduler.Pool.set_pool pool;
 
   let _pid = _spawn ~pool ~scheduler:sch0 main in
+  let () = started := true in
```
Comment (leostera) [inline riot/riot.ml:36]: **small fix.** I think we can move this line up to line 18 (so right after the if) and use the syntax `started := true;`

**Review by leostera — APPROVED** [review]
LGTM! ✨
